"""
イベントマスターデータ定義（16イベント）

scheduler_orchestrator.py seed で DB に upsert される。
"""

EVENT_MASTERS: list[dict] = [
    {
        "event_id": "US_FOMC",
        "name": "FOMC Statement & Press Conference",
        "name_ja": "FOMC 声明・記者会見",
        "region": "US",
        "category": "central_bank",
        "importance": "critical",
        "source_url": "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
        "source_type": "html",
        "release_time_rule": {"hour": 14, "minute": 0, "tz": "America/New_York"},
        "has_press_conference": True,
        "jp_follow_required": True,
    },
    {
        "event_id": "US_CPI",
        "name": "Consumer Price Index",
        "name_ja": "消費者物価指数",
        "region": "US",
        "category": "statistics",
        "importance": "critical",
        "source_url": "https://www.bls.gov/schedule/news_release/cpi.htm",
        "source_type": "html",
        "release_time_rule": {"hour": 8, "minute": 30, "tz": "America/New_York"},
        "has_press_conference": False,
        "jp_follow_required": True,
    },
    {
        "event_id": "US_EMPLOYMENT",
        "name": "Employment Situation",
        "name_ja": "雇用統計",
        "region": "US",
        "category": "statistics",
        "importance": "critical",
        "source_url": "https://www.bls.gov/schedule/news_release/empsit.htm",
        "source_type": "html",
        "release_time_rule": {"hour": 8, "minute": 30, "tz": "America/New_York"},
        "has_press_conference": False,
        "jp_follow_required": True,
    },
    {
        "event_id": "US_PCE",
        "name": "PCE Price Index",
        "name_ja": "PCE物価指数",
        "region": "US",
        "category": "statistics",
        "importance": "high",
        "source_url": "https://www.bea.gov/data/personal-consumption-expenditures-price-index",
        "source_type": "html",
        "release_time_rule": {"hour": 8, "minute": 30, "tz": "America/New_York"},
        "has_press_conference": False,
        "jp_follow_required": True,
    },
    {
        "event_id": "US_GDP",
        "name": "GDP Advance Estimate",
        "name_ja": "GDP 速報値",
        "region": "US",
        "category": "statistics",
        "importance": "high",
        "source_url": "https://www.bea.gov/data/gdp/gross-domestic-product",
        "source_type": "html",
        "release_time_rule": {"hour": 8, "minute": 30, "tz": "America/New_York"},
        "has_press_conference": False,
        "jp_follow_required": False,
    },
    {
        "event_id": "US_RETAIL_SALES",
        "name": "Retail Sales",
        "name_ja": "小売売上高",
        "region": "US",
        "category": "statistics",
        "importance": "high",
        "source_url": "https://www.census.gov/retail/index.html",
        "source_type": "html",
        "release_time_rule": {"hour": 8, "minute": 30, "tz": "America/New_York"},
        "has_press_conference": False,
        "jp_follow_required": False,
    },
    {
        "event_id": "US_ISM_MFG",
        "name": "ISM Manufacturing PMI",
        "name_ja": "ISM 製造業",
        "region": "US",
        "category": "statistics",
        "importance": "high",
        "source_url": "https://www.ismworld.org/supply-management-news-and-reports/reports/ism-report-on-business/",
        "source_type": "html",
        "release_time_rule": {"hour": 10, "minute": 0, "tz": "America/New_York"},
        "has_press_conference": False,
        "jp_follow_required": False,
    },
    {
        "event_id": "US_ISM_SVC",
        "name": "ISM Services PMI",
        "name_ja": "ISM 非製造業",
        "region": "US",
        "category": "statistics",
        "importance": "high",
        "source_url": "https://www.ismworld.org/supply-management-news-and-reports/reports/ism-report-on-business/",
        "source_type": "html",
        "release_time_rule": {"hour": 10, "minute": 0, "tz": "America/New_York"},
        "has_press_conference": False,
        "jp_follow_required": False,
    },
    {
        "event_id": "JP_BOJ",
        "name": "BOJ Monetary Policy Meeting",
        "name_ja": "日銀金融政策決定会合",
        "region": "JP",
        "category": "central_bank",
        "importance": "critical",
        "source_url": "https://www.boj.or.jp/mopo/mpmsche_minu/index.htm",
        "source_type": "html",
        "release_time_rule": {"hour": 12, "minute": 0, "tz": "Asia/Tokyo"},
        "has_press_conference": True,
        "jp_follow_required": False,
    },
    {
        "event_id": "JP_CPI_NATIONAL",
        "name": "National CPI",
        "name_ja": "全国CPI",
        "region": "JP",
        "category": "statistics",
        "importance": "high",
        "source_url": "https://www.stat.go.jp/data/cpi/index.htm",
        "source_type": "html",
        "release_time_rule": {"hour": 8, "minute": 30, "tz": "Asia/Tokyo"},
        "has_press_conference": False,
        "jp_follow_required": False,
    },
    {
        "event_id": "JP_CPI_TOKYO",
        "name": "Tokyo CPI",
        "name_ja": "東京CPI",
        "region": "JP",
        "category": "statistics",
        "importance": "high",
        "source_url": "https://www.stat.go.jp/data/cpi/index.htm",
        "source_type": "html",
        "release_time_rule": {"hour": 8, "minute": 30, "tz": "Asia/Tokyo"},
        "has_press_conference": False,
        "jp_follow_required": False,
    },
    {
        "event_id": "JP_GDP",
        "name": "GDP Preliminary",
        "name_ja": "GDP 速報値",
        "region": "JP",
        "category": "statistics",
        "importance": "high",
        "source_url": "https://www.esri.cao.go.jp/jp/sna/menu.html",
        "source_type": "html",
        "release_time_rule": {"hour": 8, "minute": 50, "tz": "Asia/Tokyo"},
        "has_press_conference": False,
        "jp_follow_required": False,
    },
    {
        "event_id": "JP_TANKAN",
        "name": "Tankan Survey",
        "name_ja": "日銀短観",
        "region": "JP",
        "category": "statistics",
        "importance": "high",
        "source_url": "https://www.boj.or.jp/statistics/tk/index.htm",
        "source_type": "html",
        "release_time_rule": {"hour": 8, "minute": 50, "tz": "Asia/Tokyo"},
        "has_press_conference": False,
        "jp_follow_required": False,
    },
    {
        "event_id": "EU_ECB",
        "name": "ECB Interest Rate Decision",
        "name_ja": "ECB 政策金利決定",
        "region": "EU",
        "category": "central_bank",
        "importance": "critical",
        "source_url": "https://www.ecb.europa.eu/press/govcdec/mopo/html/index.en.html",
        "source_type": "html",
        "release_time_rule": {"hour": 14, "minute": 15, "tz": "Europe/Frankfurt"},
        "has_press_conference": True,
        "jp_follow_required": True,
    },
    {
        "event_id": "EU_HICP",
        "name": "HICP Flash Estimate",
        "name_ja": "HICP 速報値",
        "region": "EU",
        "category": "statistics",
        "importance": "high",
        "source_url": "https://ec.europa.eu/eurostat/web/hicp",
        "source_type": "html",
        "release_time_rule": {"hour": 11, "minute": 0, "tz": "Europe/Luxembourg"},
        "has_press_conference": False,
        "jp_follow_required": True,
    },
    {
        "event_id": "EU_GDP",
        "name": "GDP Flash Estimate",
        "name_ja": "GDP 速報値",
        "region": "EU",
        "category": "statistics",
        "importance": "medium",
        "source_url": "https://ec.europa.eu/eurostat/web/national-accounts",
        "source_type": "html",
        "release_time_rule": {"hour": 11, "minute": 0, "tz": "Europe/Luxembourg"},
        "has_press_conference": False,
        "jp_follow_required": False,
    },
]
